"""add mitre column to alerts

Revision ID: 14380779d31f
Revises: bee74f1d52b2
Create Date: 2026-07-14 21:00:40.242220

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14380779d31f"
down_revision: Union[str, Sequence[str], None] = "bee74f1d52b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "alerts",
        sa.Column(
            "mitre",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default="{}",
        ),
    )
    op.alter_column("alerts", "mitre", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "mitre")
    # ### end Alembic commands ###
