"""add blocked_ips and audit_log tables

Revision ID: bee74f1d52b2
Revises: 267959e7e3c5
Create Date: 2026-06-09 17:55:03.957571

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bee74f1d52b2"
down_revision: Union[str, Sequence[str], None] = "267959e7e3c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("target_ip", sa.String(length=64), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_log_action", "audit_log", ["action"], unique=False)
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"], unique=False)
    op.create_index("ix_audit_log_target_ip", "audit_log", ["target_ip"], unique=False)
    op.create_table(
        "blocked_ips",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("blocked_by", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_blocked_ips_expires_at", "blocked_ips", ["expires_at"], unique=False)
    op.create_index("ix_blocked_ips_ip", "blocked_ips", ["ip"], unique=False)
    op.create_index("ix_blocked_ips_is_active", "blocked_ips", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_blocked_ips_is_active", table_name="blocked_ips")
    op.drop_index("ix_blocked_ips_ip", table_name="blocked_ips")
    op.drop_index("ix_blocked_ips_expires_at", table_name="blocked_ips")
    op.drop_table("blocked_ips")
    op.drop_index("ix_audit_log_target_ip", table_name="audit_log")
    op.drop_index("ix_audit_log_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_action", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
